-- Issues (or reuses) the parent-facing start-OTP for a single-day booking.
-- Called when the parent opens the booking while it is START_JOB; the code is
-- read to the provider, who enters it to move the job to IN_PROGRESS.
-- Reuse-while-valid: if a non-expired Pending OTP already exists it is returned
-- unchanged (so the code the parent already read to the provider keeps working);
-- otherwise stale Pending rows are expired and @NewCode is inserted with a
-- @TtlMinutes window. The random code is generated by the caller (app layer).
-- THROW 51130 booking not found.
--
-- This runs precisely when the parent is shown their code, which makes it the one
-- honest place to record WHERE they were when they showed it. The fix is written
-- in the same transaction that issues the code, so the two cannot come apart.
-- [CapturedById] is the booking's own PetParentId rather than anything the caller
-- passed; a Custom walk-in has no parent and so can never produce this row (nor
-- can it reach here — the parent host is the only caller).
CREATE OR ALTER PROCEDURE [Booking].[IssueBookingStartOtp]
    @BookingId UNIQUEIDENTIFIER,
    @NewCode NVARCHAR(6),
    @TtlMinutes INT = 10,
    -- The parent's position when the code was put on screen. See
    -- [Booking].[StartBooking] for why these are defaulted to NULL.
    @Latitude DECIMAL(9, 6) = NULL,
    @Longitude DECIMAL(9, 6) = NULL,
    @AccuracyMetres DECIMAL(9, 2) = NULL,
    @DeviceCapturedAtUtc DATETIME2(7) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @Now DATETIME2(7) = SYSUTCDATETIME();
    DECLARE @RowProvider UNIQUEIDENTIFIER;
    DECLARE @RowPetParent UNIQUEIDENTIFIER;

    BEGIN TRANSACTION;

    -- [ProviderId] is NOT NULL, so it doubles as the existence check — unlike
    -- [PetParentId], which is legitimately NULL on a Custom walk-in.
    SELECT @RowProvider = [ProviderId], @RowPetParent = [PetParentId]
    FROM [Booking].[Bookings] WITH (UPDLOCK, HOLDLOCK)
    WHERE [BookingId] = @BookingId;

    IF @RowProvider IS NULL
    BEGIN
        THROW 51130, 'Booking was not found.', 1;
    END

    -- Expire any Pending OTPs that have passed their window.
    UPDATE [Booking].[BookingStartOtps]
    SET [Status] = N'Expired'
    WHERE [BookingId] = @BookingId
      AND [Status] = N'Pending'
      AND [ExpiresAtUtc] <= @Now;

    DECLARE @ActiveId UNIQUEIDENTIFIER;
    SELECT TOP (1) @ActiveId = [BookingStartOtpId]
    FROM [Booking].[BookingStartOtps] WITH (UPDLOCK, HOLDLOCK)
    WHERE [BookingId] = @BookingId
      AND [Status] = N'Pending'
      AND [ExpiresAtUtc] > @Now
    ORDER BY [IssuedAtUtc] DESC;

    IF @ActiveId IS NULL
    BEGIN
        DECLARE @Inserted TABLE ([BookingStartOtpId] UNIQUEIDENTIFIER);
        INSERT INTO [Booking].[BookingStartOtps]
            ([BookingId], [OtpCode], [ExpiresAtUtc])
        OUTPUT inserted.[BookingStartOtpId] INTO @Inserted
        VALUES (@BookingId, @NewCode, DATEADD(MINUTE, @TtlMinutes, @Now));

        SELECT @ActiveId = [BookingStartOtpId] FROM @Inserted;
    END

    -- This sproc runs precisely when the parent is shown the code, so it is the
    -- honest place to record that they have seen it. COALESCE keeps the FIRST
    -- sighting: the nudge that branches on this asks "have they opened it at
    -- all?", and re-opening the screen must not reset that answer.
    UPDATE [Booking].[BookingStartOtps]
    SET [SeenAtUtc] = COALESCE([SeenAtUtc], @Now)
    WHERE [BookingStartOtpId] = @ActiveId;

    -- Where the parent was when they showed the code. Unlike [SeenAtUtc] above
    -- this is NOT collapsed to the first sighting: re-opening the screen is a
    -- fresh claim about where they are, and each one is worth keeping.
    IF @Latitude IS NOT NULL AND @Longitude IS NOT NULL AND @RowPetParent IS NOT NULL
    BEGIN
        INSERT INTO [Booking].[BookingLocationEvents]
            ([BookingId], [Trigger], [CapturedByType], [CapturedById],
             [Latitude], [Longitude], [AccuracyMetres], [DeviceCapturedAtUtc])
        VALUES
            (@BookingId, N'StartOtpShown', N'Parent', @RowPetParent,
             @Latitude, @Longitude, @AccuracyMetres, @DeviceCapturedAtUtc);
    END

    SELECT [BookingStartOtpId], [BookingId], [OtpCode], [Status], [IssuedAtUtc], [ExpiresAtUtc]
    FROM [Booking].[BookingStartOtps]
    WHERE [BookingStartOtpId] = @ActiveId;

    COMMIT TRANSACTION;
END;
