-- Issues (or reuses) the start-job OTP for a single-day booking. Called when the
-- parent opens the booking details. Reuse-while-valid: if a non-expired Pending
-- OTP already exists it is returned unchanged (so the code the parent already
-- read to the provider keeps working); otherwise stale Pending rows are expired
-- and @NewCode is inserted with a @TtlMinutes window. The random code is
-- generated by the caller (app layer). THROW 51130 booking not found.
CREATE OR ALTER PROCEDURE [Booking].[IssueBookingStartOtp]
    @BookingId UNIQUEIDENTIFIER,
    @NewCode NVARCHAR(6),
    @TtlMinutes INT = 10
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @Now DATETIME2(7) = SYSUTCDATETIME();

    BEGIN TRANSACTION;

    IF NOT EXISTS (
        SELECT 1 FROM [Booking].[Bookings] WITH (UPDLOCK, HOLDLOCK)
        WHERE [BookingId] = @BookingId)
    BEGIN
        THROW 51130, 'Booking was not found.', 1;
    END

    -- Expire any Pending OTPs that have passed their window.
    UPDATE [Booking].[BookingStartOtps]
    SET [Status] = N'Expired'
    WHERE [BookingId] = @BookingId
      AND [Status] = N'Pending'
      AND [ExpiresAtUtc] <= @Now;

    DECLARE @ActiveId UNIQUEIDENTIFIER;
    SELECT TOP (1) @ActiveId = [BookingStartOtpId]
    FROM [Booking].[BookingStartOtps] WITH (UPDLOCK, HOLDLOCK)
    WHERE [BookingId] = @BookingId
      AND [Status] = N'Pending'
      AND [ExpiresAtUtc] > @Now
    ORDER BY [IssuedAtUtc] DESC;

    IF @ActiveId IS NULL
    BEGIN
        DECLARE @Inserted TABLE ([BookingStartOtpId] UNIQUEIDENTIFIER);
        INSERT INTO [Booking].[BookingStartOtps]
            ([BookingId], [OtpCode], [ExpiresAtUtc])
        OUTPUT inserted.[BookingStartOtpId] INTO @Inserted
        VALUES (@BookingId, @NewCode, DATEADD(MINUTE, @TtlMinutes, @Now));

        SELECT @ActiveId = [BookingStartOtpId] FROM @Inserted;
    END

    SELECT [BookingStartOtpId], [BookingId], [OtpCode], [Status], [IssuedAtUtc], [ExpiresAtUtc]
    FROM [Booking].[BookingStartOtps]
    WHERE [BookingStartOtpId] = @ActiveId;

    COMMIT TRANSACTION;
END;
